### ISSUE TITLE
Hash User Passwords in Database

### ISSUE THREAD

**Issue by darneymartin** [m8r0wn/transportc2#1]
Functions to hash and check user passwords need to be created so that passwords are not stored in plain text.

**Comment by m8r0wn** [comment]
Passwords have been MD5 hashed to prevent the plain-text values being stored in the database.

![screen shot 2019-01-16 at 8 05 04 am](https://user-images.githubusercontent.com/13889819/51250913-f25bbb00-1965-11e9-8a0c-8047417821f3.png)

-m8r0wn
